json.id                  @platform.id
json.name                @platform.name
json.media_type_id       @platform.media_type_id
json.dfp_key             @platform.dfp_key
json.site_id             @platform.site_id
json.dfp_site_name       @platform.site.name
json.naming_convention   @platform.naming_convention
json.ad_type             @platform.ad_type
json.priority            @platform.priority
json.enabled             @platform.enabled