#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential', '~> 1.4.4'

cookbook 'java',
  :git => 'https://github.com/socrata-cookbooks/java'

cookbook 'ruby_build',
  :git => 'https://github.com/fnichol/chef-ruby_build', :ref => 'v0.8.0'

cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv', :ref => 'v0.7.2'

cookbook 'git', 
  :git => 'https://github.com/jssjr/git'

cookbook 'postgresql',
  :git => 'https://github.com/hw-cookbooks/postgresql'
