# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure your secret_key_base is kept private
# if you're sharing your code publicly.

key: _reachui_session
secret_key_base: 0d8971419f4f07a296f0eb44a9383a6e35358679e4237f8eeffa9c2eedb03a544b37e4d6538de01e14f267c3a68082974b2acf94eb4ea80a807d76cb9d0d8b63


development:
  domain: '.dev.collective.com'

test:
  domain: :all

qa:
  domain: 'qa-reach.collective.com'

newqa: 
  domain: 'qa-desk.collective.com'

newstg:
  domain: 'demo-desk.collective.com'

production:
  domain: 'reach.collective.com'
