json.id @nielsen_campaign.id
json.name @nielsen_campaign.name
json.cost_type @nielsen_campaign.cost_type
json.value @nielsen_campaign.value
json.trp_goal @nielsen_campaign.trp_goal
json.target_gender @nielsen_campaign.target_gender
json.age_range age_range(@nielsen_campaign)
json.source_id @nielsen_campaign.source_id
json.order_id @nielsen_campaign.order_id
