json.id @nielsen_campaign.id
json.name @nielsen_campaign.name
json.cpp_value @nielsen_campaign.cpp_value
json.imps_value @nielsen_campaign.imps_value
json.trp_goal @nielsen_campaign.trp_goal
json.target_gender @nielsen_campaign.target_gender
json.age_range age_range(@nielsen_campaign)
json.source_id @nielsen_campaign.source_id
json.order_id @nielsen_campaign.order_id
