#!/bin/bash
#
#   /etc/init.d/crpt-ui
#   chkconfig: 2345 90 60
#
#   This Starts CRPT UI. Scala REST Application.
#

# Source function library.
. /etc/init.d/functions

# You can set Java home to pass a java home for play application, else java from the path will be used to run CRPT UI.
JAVA_HOME='/usr/java/default'

CRPT_UI_USER=amp
CRPT_UI_HOME="/home/amp/crpt-ui"
CRPT_UI_PID=${CRPT_UI_HOME}/crpt-ui.pid
CRPT_UI_LOCK=/var/lock/subsys/crpt-ui
ADDRESS=`/sbin/ifconfig eth0|grep -i 'inet addr'|cut -d ':' -f 2|cut -d ' ' -f1`
PORT=8080
CRPT_UI_CONFIG=${CRPT_UI_HOME}/crpt-ui-1.0-SNAPSHOT/conf/application.conf
CRPT_UI_LOG_DIR=$CRPT_UI_HOME/log


start() {
	if [ -f $CRPT_UI_PID ] || [ -f  $CRPT_UI_LOCK ] ; then
		echo " CRPT_UI is already started "
		exit -1
	fi
	echo -n "Starting crpt-ui on port $ADDRESS:$PORT : "
	su $CRPT_UI_USER -c  "${CRPT_UI_HOME}/crpt-ui-1.0-SNAPSHOT/bin/crpt-ui -J-Xmx8192m -Dpidfile.path=$CRPT_UI_PID  -Dhttp.port=$PORT -Dlogger.resource=${CRPT_UI_HOME}/crpt-ui-1.0-SNAPSHOT/conf/application-logger.xml -Dconfig.file=$CRPT_UI_CONFIG 2>&1 >> $CRPT_UI_LOG_DIR/application.log & echo$!" 
        retval=$?
        if [ $retval == 0 ] ; then
	  touch $CRPT_UI_LOCK
	  exit $retval
          fi
}

stop() {
	echo -n "Shutting down crpt-ui: "
	if [ ! -f $CRPT_UI_PID ] ; then
		echo -n "Application not started. Pidfile does not exist."
		rm -f $CRPT_UI_LOCK
                exit 0
	fi
	##killing the process for server shutdown,
	kill -9 `cat $CRPT_UI_PID`
    retval=$?
	rm -f $CRPT_UI_LOCK
	rm -f $CRPT_UI_PID
	return $retval
}
status() {
  [ -f $CRPT_UI_PID ] && echo "crpt-ui running, $(cat $CRPT_UI_PID)" || echo "crpt-ui is not running"
}

case "$1" in
    start)
	    start
	    ;;
    stop)
	    stop
	    ;;
    status)
      status
      ;;
    restart)
      stop
	    start
	    ;;
    *)
	    echo "Usage: crpt-ui {start|stop|restart}"
	    exit 1
	    ;;

esac

exit $?
